## Data Science with Python

### Introduction to Python

Python is a computer programming language often used to build  **websites and software, automate tasks, and conduct data analysis.**


## Data Types

- Integer
- Float
- Strings
- Booleans
- Lists
- Tuples
- Sets
- Dictionaries

In [13]:
# Declare two variables and print their sum


a = 1
b = 2
print(a+b)

3


The boy is coming

# The boy is coming

In [11]:
a-b

-1

In [14]:
print(a-b)

-1


In [15]:
10 ** 2

100

In [ ]:
'''
Add two numbers 
and display their output
'''




In [17]:
a = 10
b = 5



In [16]:
type(a)

int

In [18]:
print(a+b)

15


In [19]:
a = 9

In [20]:
a

9

In [22]:
a = 9
b = 4

print(a,b)

9 4


In [23]:
10 + 9.5

19.5

In [24]:
type(19.5)

float

In [27]:
10 / 3

3.3333333333333335

In [28]:
10 // 3

3

In [29]:
10 % 3

1

In [37]:
name = 'Chuks'


In [33]:
print('Bonuola\'s a lady')

Bonuola's a lady


In [34]:
print('car' * 2)

carcar


In [35]:
age = 17
print(age * 2)

34


In [38]:
name

'Chuks'

In [39]:
dir(name)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [40]:
sentence = 'this is data science class'
sentence

'this is data science class'

In [41]:
sentence.capitalize()

'This is data science class'

In [42]:
sentence.upper()

'THIS IS DATA SCIENCE CLASS'

In [43]:
sentence.title()

'This Is Data Science Class'

In [44]:
sentence.split()

['this', 'is', 'data', 'science', 'class']

In [45]:
sentence.isalpha()

False

In [46]:
name.isalpha()

True

In [48]:
sent = 'ThisIsDataScienceClass'
sent

'ThisIsDataScienceClass'

In [49]:
sent.isalpha()

True

In [55]:
# .count() as a string method returns the count of specified character(s)
sentence.count('s')

5

In [56]:
sentence

'this is data science class'

In [57]:
sentence.rstrip()

'this is data science class'

In [58]:
len(name)

5

In [59]:
# len returns the number of characters

len(sentence)

26

In [60]:
# \n goes to a new line

print('My name is Chinazam\nI am a member of this class')

My name is Chinazam
I am a member of this class


In [61]:
# \t goes to a new tab

print('My name is Chinazam\tI am a member of this class')

My name is Chinazam	I am a member of this class


In [76]:
# a small program that returns a person's full name

f_name = input('What is your first name? >>> ')
f_name = f_name.capitalize()
l_name = input('What is your last name? >>> ')
l_name = l_name.capitalize()

full_name = f_name + ' ' + l_name

print(full_name)

What is your first name? >>> chinazam
What is your last name? >>> akagha
Chinazam Akagha


In [74]:
name_1 = 'Chinazam'
name_2 = 'chinazam'
name_3 = 'Chinazam'

print(name_1, name_2, name_3, sep=" ")

Chinazam chinazam Chinazam


In [75]:
name_1 == name_3

True

### Indexing and Slicing
- Indexing is used to obtain individual elements
- Slicing is used to obtain a sequence of elements

Indexing starts from 0, that is, the first element in the sequence is index 0.
Negative indexing starts -1 

In [84]:
country_1 = 'Argentina'
country_2 = 'Netherlands'
country_3 = 'Zimbabwe'

print(country_1, country_2, country_3, sep='\n')

Argentina
Netherlands
Zimbabwe


In [ ]:
# print, sum, len, list, tuple, help, dir, 
# country_1.capitalize(), name.upper()

In [85]:
country_1[0]

'A'

In [86]:
country_1[5]

't'

In [87]:
country_2[7]

'a'

In [88]:
country_2[-4]

'a'

In [ ]:
# [Start:Stop:Step]

In [89]:
country_3

'Zimbabwe'

In [90]:
country_3[:]

'Zimbabwe'

In [91]:
country_3[:5]

'Zimba'

In [92]:
country_3[2:6]

'mbab'

In [ ]:
country_2[4:7]

In [95]:
country_3[::2]

'Zmaw'

In [96]:
country_2[2:8:3]

'tr'

In [97]:
country_2

'Netherlands'

In [98]:
country_2[1::3]

'eeas'

In [101]:
country_2[-1::3]

's'

In [103]:
country_2[-1::-3]

'saee'

In [104]:
country_2[7::-3]

'aee'

In [105]:
sentence

'this is data science class'

In [106]:
sentence[2:20:2]

'i sdt cec'

In [107]:
numbers = '123456789'

In [112]:
numbers[2:8:6]

'3'

## Print Formatting

In [113]:
name = 'Fred'
age = 24

print('My name is', name, 'I am', age, 'years old')

My name is Fred I am 24 years old


In [114]:
name = 'Fred'
age = 24

print('My name is name I am age years old')

My name is name I am age years old


In [115]:
name = 'Fred'
age = 24

print('My name is' name 'I am' age 'years old')

SyntaxError: invalid syntax (<ipython-input-115-a21b84ca3ac3>, line 4)

In [116]:
# .format()


print('My name is {} and I am {} years old'.format(name,age))


My name is Fred and I am 24 years old


In [117]:
# .format()
# implication of swapping the variable

print('My name is {} and I am {} years old'.format(age,name))


My name is 24 and I am Fred years old


In [121]:
# Placeholder

height = 5.5
weight = 70.5

print('My name is %s \nI am %s years old \nI am %s feet in height and \nI weigh %s kg'%(name,age, height, weight))

My name is Fred 
I am 24 years old 
I am 5.5 feet in height and 
I weigh 70.5 kg


In [122]:
# f-string
print(f'My name is {name} \nI am {age} years old \nI am {height} feet in height and \nI weigh {weight} kg')

My name is Fred 
I am 24 years old 
I am 5.5 feet in height and 
I weigh 70.5 kg


## List
A List is an **ordered sequence of items**.

It is a very flexible data type in Python. There is no need for the value in the list to be of the same data type. 

The List is the data type that is highly used data type in Python. List datatype is the most exclusive datatype in Python for containing versatile data. It can easily hold different types of data in Python.



In [ ]:
# []

In [124]:
name = ['Chike', 'Kunle', 'Bolu', 'Taiwo', 'Chuks']
name

['Chike', 'Kunle', 'Bolu', 'Taiwo', 'Chuks']

In [125]:
type(name)

list

In [126]:
numbers = [10, 25.9, 60, 15.5, 120]
numbers

[10, 25.9, 60, 15.5, 120]

In [129]:
someItems = ['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi']
someItems

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi']

In [130]:
someItems[0]

'Abidemi'

In [131]:
someItems[-1]

'Aderemi'

In [132]:
someItems[1:4:2]

[26, 56.3]

In [136]:
someItems[::3]

['Abidemi', 56.3]

In [135]:
someItems.index('Abidemi')

0

In [137]:
dir(someItems)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [138]:
someItems

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi']

In [139]:
some_items = someItems + ['Funmi']
some_items

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi', 'Funmi']

In [141]:
someItems = someItems + ['Fred']

In [142]:
someItems

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi', 'Fred']

In [144]:
someItems.append(True)
someItems

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi', 'Fred', True, True]

In [145]:
some_items.clear()
some_items


[]

In [147]:
someItems_1 = someItems.copy()
someItems_1

['Abidemi', 26, False, 56.3, '10Alytics', 'Aderemi', 'Fred', True, True]

In [148]:
someItems.count(True)

2

In [149]:
someItems.count('10Alytics')

1

In [150]:
len(someItems)

9

In [152]:
someItems.extend(['Car','Phone'])
someItems

['Abidemi',
 26,
 False,
 56.3,
 '10Alytics',
 'Aderemi',
 'Fred',
 True,
 True,
 'Car',
 'Phone']

In [153]:
someItems.index('Car')

9

In [154]:
someItems.insert(1,'Chinazam')
someItems

['Abidemi',
 'Chinazam',
 26,
 False,
 56.3,
 '10Alytics',
 'Aderemi',
 'Fred',
 True,
 True,
 'Car',
 'Phone']

In [155]:
someItems[0] = 'Chinazam'
someItems

['Chinazam',
 'Chinazam',
 26,
 False,
 56.3,
 '10Alytics',
 'Aderemi',
 'Fred',
 True,
 True,
 'Car',
 'Phone']

In [157]:
someItems.pop()
someItems

['Chinazam',
 'Chinazam',
 26,
 False,
 56.3,
 '10Alytics',
 'Aderemi',
 'Fred',
 True,
 True]

In [158]:
someItems.remove(True)
someItems

['Chinazam', 'Chinazam', 26, False, 56.3, '10Alytics', 'Aderemi', 'Fred', True]

In [160]:
someItems.remove('10Alytics')
someItems

['Chinazam', 'Chinazam', 26, False, 56.3, 'Aderemi', 'Fred', True]

In [161]:
someItems.reverse()
someItems

[True, 'Fred', 'Aderemi', 56.3, False, 26, 'Chinazam', 'Chinazam']

In [165]:
someItems.remove(True)
someItems

['Fred', 'Aderemi', 56.3, False, 26, 'Chinazam', 'Chinazam']

In [166]:
someItems.remove(False)
someItems

['Fred', 'Aderemi', 56.3, 26, 'Chinazam', 'Chinazam']

In [167]:
someItems.sort()
someItems

TypeError: '<' not supported between instances of 'float' and 'str'

In [168]:
someNumbers = [12,6,18,87,40,56,45,3]


In [169]:
someNumbers.sort()
someNumbers

[3, 6, 12, 18, 40, 45, 56, 87]

In [172]:
someNumbers.sort(reverse=True)
someNumbers

[87, 56, 45, 40, 18, 12, 6, 3]

In [170]:
someNames = ['Taiwo','Adeola','Chinazam','Segun','Chike']

In [171]:
someNames.sort()
someNames

['Adeola', 'Chike', 'Chinazam', 'Segun', 'Taiwo']

In [173]:
someNames.sort(reverse=True)
someNames

['Taiwo', 'Segun', 'Chinazam', 'Chike', 'Adeola']

In [174]:
# Nested List

persons = ['Bonuola','Juliet','Cynthia', ['Asake', 'Davido', 'Chike'], ['Messi','Ronaldo','Rashford']]
persons

['Bonuola',
 'Juliet',
 'Cynthia',
 ['Asake', 'Davido', 'Chike'],
 ['Messi', 'Ronaldo', 'Rashford']]

In [175]:
persons[0]

'Bonuola'

In [176]:

persons[3]

['Asake', 'Davido', 'Chike']

In [177]:
# Accessing an item in a nested list

persons[3][0]

'Asake'

In [178]:
persons[4][2]

'Rashford'

In [ ]:
cars = [['Toyota', 'Honda', 'Nissan', 'Benz'], ['Yellow','Red','Blue']]

## Dictionaries
Dictionary is a type of python data type in which collections are **unordered**, and **values** are in pairs called **key-value pairs**.

 This type of data type is useful when there is a high volume of data. Braces {} (curly brackets) are used to define dictionaries data type in Python. A Pair in the dictionary data type is an item which is represented as key:value. **The value and the key can be of any data type.**

In [179]:

# curly braces {}

mydict = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
mydict

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

In [180]:
type(mydict)

dict

In [182]:
mydict['key2']

'value2'

In [183]:
animals = {'dog': 'Bingo', 'cat': 'Musu', 'monkey': 'Jalingo'}
animals

{'dog': 'Bingo', 'cat': 'Musu', 'monkey': 'Jalingo'}

In [184]:
animals['dog']

'Bingo'

In [ ]:
# xlsx, csv, tar, sql, json 

In [185]:
customer = {'name': 'Jason', 'address': '10 Owo Drive, Lagos', 'age': 45, 'gender': 'male', 'phone number': '08035555558', 
           'weight': 70, 'height': 175}
customer

{'name': 'Jason',
 'address': '10 Owo Drive, Lagos',
 'age': 45,
 'gender': 'male',
 'phone number': '08035555558',
 'weight': 70,
 'height': 175}

In [186]:
customer['name']

'Jason'

In [187]:
customer['address']

'10 Owo Drive, Lagos'

In [188]:
customer['age']

45

In [204]:
cust = {'names': ['Bolu', 'Ibrahim', 'Cynthia', 'Adeola'], 'ages': [23,45,67,98], 'colours':['Red','Yellow']}
cust

{'names': ['Bolu', 'Ibrahim', 'Cynthia', 'Adeola'],
 'ages': [23, 45, 67, 98],
 'colours': ['Red', 'Yellow']}

In [191]:
cust['names'][1]

'Ibrahim'

In [203]:
empty = {'names':'girl', 'names':'boy'}
empty

{'names': 'boy'}

In [206]:
cust['colours'][1]

'Yellow'

In [207]:
mydict_1 = {}
mydict_1

{}

In [208]:
mydict_1['name'] = 'Michael'
mydict_1['state_of_origin'] = 'Oyo'
mydict_1['qualification'] = 'BSc'

mydict_1

{'name': 'Michael', 'state_of_origin': 'Oyo', 'qualification': 'BSc'}

In [212]:
mydict_2 = {'party':'Democrats'}
mydict_2

{'party': 'Democrats'}

In [213]:
mydict_3 = [mydict_1, mydict_2]
mydict_3

[{'name': 'Michael', 'state_of_origin': 'Oyo', 'qualification': 'BSc'},
 {'party': 'Democrats'}]

In [216]:
dir(mydict_1)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [218]:
# .get returns the value contained in a key when the key is accessed

mydict_1.get('name')

'Michael'

In [219]:
mydict_1.items()

dict_items([('name', 'Michael'), ('state_of_origin', 'Oyo'), ('qualification', 'BSc')])

In [220]:
mydict_1.update(mydict_2)
mydict_1

{'name': 'Michael',
 'state_of_origin': 'Oyo',
 'qualification': 'BSc',
 'party': 'Democrats'}

In [ ]:
dictname['key'] = 'value'

In [209]:
cust

{'names': ['Bolu', 'Ibrahim', 'Cynthia', 'Adeola'],
 'ages': [23, 45, 67, 98],
 'colours': ['Red', 'Yellow']}

In [210]:
cust['complexion'] = 'Fair'

cust

{'names': ['Bolu', 'Ibrahim', 'Cynthia', 'Adeola'],
 'ages': [23, 45, 67, 98],
 'colours': ['Red', 'Yellow'],
 'complexion': 'Fair'}

## Tuple

A Tuple is a sequence of items that are in **order**, and it is not possible to modify the Tuples. 

**The main difference list and tuples are that tuple is immutable, which means it cannot be altered**. 

- Tuples are generally faster than the list data type in Python because it cannot be changed or modified like list datatype. 
- The primary use of Tuples is to write-protect data. 
- Tuples can be represented by using parentheses (), and 
- commas are used to separate the items. 

Days of the week, Months of the year, DOB, etc

In [221]:
# list

names = ['Chinazam','Tosin','Muiz']
names

['Chinazam', 'Tosin', 'Muiz']

In [222]:
names[0] = 'Adeola'
names

['Adeola', 'Tosin', 'Muiz']

In [224]:
# Tuples ()

name = ('Chinazam', 'Tosin', 'Muiz')
name

('Chinazam', 'Tosin', 'Muiz')

In [225]:
# tuples are immutable and will not allow alteration

name[0] = 'Adeola'

TypeError: 'tuple' object does not support item assignment

In [226]:
name[0]

'Chinazam'

## Set

A Set is a collection of **Unique items that are not in order is called Set**. 

Braces **{   }** are used to defined set and a comma is used to separate values. 

One will find that the items are unordered in a set data type.

- Duplicates are eliminated in a set and set only keeps unique values. 
- Operations like intersection and union can be performed on two sets. 

In [227]:
myset = {2,2,2,2,2,2,2,2,2,2,3,4,5,5,5,6,7,8,8,8,9}
myset

{2, 3, 4, 5, 6, 7, 8, 9}

In [237]:
# a list

names = ['Victor', 'Funmi', 'Shade', 'John','Adewale', 'John', 'Victor']
names

['Victor', 'Funmi', 'Shade', 'John', 'Adewale', 'John', 'Victor']

In [230]:
type(names)

list

In [231]:
# convert a list to tuple

names = tuple(names)
names

('Victor', 'Funmi', 'Shade', 'John', 'Adewale')

In [232]:
type(names)

tuple

In [233]:
# tuple

ages = (23, 45, 67, 98)
ages

(23, 45, 67, 98)

In [234]:
type(ages)

tuple

In [235]:
# convert tuple to a list

ages = list(ages)
ages

[23, 45, 67, 98]

In [236]:
names

('Victor', 'Funmi', 'Shade', 'John', 'Adewale')

In [238]:
names 

['Victor', 'Funmi', 'Shade', 'John', 'Adewale', 'John', 'Victor']

In [239]:
# convert a list to set

names = set(names)
names

{'Adewale', 'Funmi', 'John', 'Shade', 'Victor'}

In [240]:
numbers = {9,5,5,4,3,6,3,8,2,4,1}
numbers

{1, 2, 3, 4, 5, 6, 8, 9}

In [241]:
type(numbers)

set

In [242]:
dir(numbers)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [243]:
newset = {1,2,3,4,5,6,7}
newset2 = {1,3,5,7,9}
newset3 = {0,2,4,6,8,10}

print(newset, newset2, newset3, sep='\n')

{1, 2, 3, 4, 5, 6, 7}
{1, 3, 5, 7, 9}
{0, 2, 4, 6, 8, 10}


In [244]:
newset.add(11)
newset

{1, 2, 3, 4, 5, 6, 7, 11}

In [245]:
newset.add(10)
newset

{1, 2, 3, 4, 5, 6, 7, 10, 11}

In [246]:
newset.intersection(newset2)

{1, 3, 5, 7}

In [247]:
newset.union(newset3)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11}

In [248]:
newset.difference(newset2)

{2, 4, 6, 10, 11}

In [249]:
newset2.difference(newset)

{9}

## Booleans
There can be only two types of value in the Boolean data type of Python, and that is True or False. 

In [ ]:
# True False

In [1]:
# equal to
1 == 1

True

In [2]:
5 == 8

False

In [ ]:
True and False

## Comparison Operators
Comparison operators are used to compare two values:

* == Equal to
* != Not Equal to
* #>  Greater than
* #>= Greater than or Equal to
* <  Less than
* <= Less than or Equal to


In [3]:
# equal to
1 == 1

True

In [4]:
5 == 8

False

In [5]:
# not equal to

1 != 1

False

In [6]:
5 != 8

True

In [7]:
# greater than

10 > 20

False

In [8]:
# less than

10 < 20 

True

In [9]:
# greater than or equal to

10 >= 20

False

In [10]:
# less than or equal to

10 <= 20

True

In [11]:
'Chinyere' == 'chinyere'

False

In [12]:
'Chinyere' == 'Chinyere'

True

In [13]:
'Chinyere' != 'chinyere'

True

In [14]:
type(1==1)

bool

#### Conditional statements
Conditional statements use conditions to modify how your function runs. 

They check the value of a condition, and if the condition evaluates to True, then a certain block of code is executed. (Otherwise, if the condition is False, then the code is not run.

## If, Elif, Else Statement
The Python **if statement** is same as it is with other programming languages. 
It executes a set of statements conditionally, based on the value of a logical expression.

In Python **if .. else statement**, if has two blocks, one following the expression and other following the else clause.

The **if-elif-else statement** is used to conditionally execute a statement or a block of statements. 

Conditions can be true or false, execute one thing when the condition is true, something else when the condition is false.


In [16]:
# Example

name = 'Chinazam'

if name == 'Chinazam':
    print(f'Your name is {name}')
else: 
    print(f'Your name is not what we expect')
    

Your name is Chinazam


In [17]:
# Example

name = 'Tosin'

if name == 'Chinazam':
    print(f'Your name is {name}')
else: 
    print(f'Your name is not what we expect')
    

Your name is not what we expect


In [19]:
name = input('What is your name? ')

if name == 'Bonuola':
    print(f'Welcome to the class {name}')
else:
    print(f'You are not welcome to the class {name}')

What is your name? Abidemi
You are not welcome to the class Abidemi


In [20]:
name = input('What is your name? ')

if name == 'Bonuola':
    print(f'Welcome to the class {name}')
else:
    print(f'You are not welcome to the class {name}')

What is your name? bonuola
You are not welcome to the class bonuola


In [23]:
# Elif example

name = input('What is your name? ')

if name == 'Bonuola':
    print(f'Welcome to the class {name}')
elif name == 'Chike':
    print(f'Welcome to our palace {name}')
elif name == 'Kunle':
    print(f'Welcome to our country {name}')
elif name == 'Adeola':
    print(f'Welcome to our kingdom {name}')
elif name == 'Fred':
    print(f'Welcome to our home {name}')
else:
    print(f'We do not seem to recognise you {name}')
    

What is your name? Kunle
Welcome to our country Kunle


In [24]:
# Elif example

name = input('What is your name? ')

if name == 'Bonuola':
    print(f'Welcome to the class {name}')
elif name == 'Chike':
    print(f'Welcome to our palace {name}')
elif name == 'Kunle':
    print(f'Welcome to our country {name}')
elif name == 'Adeola':
    print(f'Welcome to our kingdom {name}')
elif name == 'Fred':
    print(f'Welcome to our home {name}')
else:
    print(f'We do not seem to recognise you {name}')
    

What is your name? Chuks
We do not seem to recognise you Chuks


In [27]:
name = input('What is your name? ')
name = name.lower()

if name == 'bonuola':
    print(f'Welcome to the class {name}')
else:
    print('You are not welcome to the class %s'%(name))

What is your name? BONUOLA
Welcome to the class bonuola


In [30]:
name = input('What is your name? ')
name = name.title()

if name == 'Bonuola':
    print(f'Welcome to the class {name}')
else:
    print('You are not welcome to the class %s'%(name))

What is your name? bONUOLA
Welcome to the class Bonuola


In [31]:
''' Return a letter grade based on a student's final score

 stud_name => student name
 first_test => score in first test
 second_test => score in second test
 attd => score in attendance
 exam => score in exam
 total_score => student's final score which is a summation of the above scores 
 assign a letter grade based on the student's final score

'''

stud_name = input('What is your name? >>>>> ')
first_test = int(input('What is your score in first test? >>>>> '))
second_test = int(input('What is your score in second test? >>>>> '))
attd = int(input('What is your score in attendance? >>>>> '))
exam = int(input('What is your score in the examination? >>>>> '))

print('----------------------------------------------------------------')

total_score = first_test + second_test + attd + exam

if total_score >= 70:
    grade = 'A'
elif total_score >= 60:
    grade = 'B'
elif total_score >= 50:
    grade = 'C'
elif total_score >= 40:
    grade = 'D'
else:
    grade = 'F'
    
print(f'Hello {stud_name}, your final score is {total_score} and your grade is {grade}')




What is your name? >>>>> Dorcas
What is your score in first test? >>>>> 20
What is your score in second test? >>>>> 15
What is your score in attendance? >>>>> 21
What is your score in the examination? >>>>> 25
----------------------------------------------------------------
Hello Dorcas, your final score is 81 and your grade is A


In [32]:
''' Return a letter grade based on a student's final score

 stud_name => student name
 first_test => score in first test
 second_test => score in second test
 attd => score in attendance
 exam => score in exam
 total_score => student's final score which is a summation of the above scores 
 assign a letter grade based on the student's final score

'''

stud_name = input('What is your name? >>>>> ')
first_test = int(input('What is your score in first test? >>>>> '))
second_test = int(input('What is your score in second test? >>>>> '))
attd = int(input('What is your score in attendance? >>>>> '))
exam = int(input('What is your score in the examination? >>>>> '))

print('----------------------------------------------------------------')

total_score = first_test + second_test + attd + exam

if total_score >= 70:
    grade = 'A'
elif total_score >= 60:
    grade = 'B'
elif total_score >= 50:
    grade = 'C'
elif total_score >= 40:
    grade = 'D'
else:
    grade = 'F'
    
print(f'Hello {stud_name}, your final score is {total_score} and your grade is {grade}')




What is your name? >>>>> Chinazam
What is your score in first test? >>>>> 6
What is your score in second test? >>>>> 11
What is your score in attendance? >>>>> 5
What is your score in the examination? >>>>> 10
----------------------------------------------------------------
Hello Chinazam, your final score is 32 and your grade is F


In [33]:
''' Return a letter grade based on a student's final score

 stud_name => student name
 first_test => score in first test
 second_test => score in second test
 attd => score in attendance
 exam => score in exam
 total_score => student's final score which is a summation of the above scores 
 assign a letter grade based on the student's final score

'''

stud_name = input('What is your name? >>>>> ')
first_test = int(input('What is your score in first test? >>>>> '))
second_test = int(input('What is your score in second test? >>>>> '))
attd = int(input('What is your score in attendance? >>>>> '))
exam = int(input('What is your score in the examination? >>>>> '))

print('----------------------------------------------------------------')

total_score = first_test + second_test + attd + exam

if total_score >= 40:
    grade = 'D'
elif total_score >= 50:
    grade = 'C'
elif total_score >= 60:
    grade = 'B'
elif total_score >= 70:
    grade = 'A'
else:
    grade = 'F'
    
print(f'Hello {stud_name}, your final score is {total_score} and your grade is {grade}')




What is your name? >>>>> Chike
What is your score in first test? >>>>> 20
What is your score in second test? >>>>> 15
What is your score in attendance? >>>>> 21
What is your score in the examination? >>>>> 25
----------------------------------------------------------------
Hello Chike, your final score is 81 and your grade is D


### Supermarket Example

Calculate a customer's discount based on some conditions 

* Customer Type = Retail or Corporate
* amount = total value of all goods purchased

* Corporate
* Discount

* amt <= 10000 = 20%
* amt <= 40000 = 25%
* amt <= 100000 = 30%
* amt > 100000 = 40%


* Retail
* Discount

* amt <= 10000 = 10%
* amt <= 40000 = 15%
* amt <= 100000 = 20%
* amt > 100000 = 30%

* print amount
* print discount
* amount due = amt-discount

In [2]:
cust_type = input('What type of customer are you?: ')
amt = float(input('What is the amount you spent?: '))
            
if cust_type == 'Corporate':
    if amt <= 10000:
        discount = 0.2
    elif amt <= 40000:
        discount = 0.25
    elif amt <= 100000:
        discount = 0.3
    else:
        discount = 0.4
elif cust_type == 'Retail':
    if amt <= 10000:
        discount = 0.1
    elif amt <= 40000:
        discount = 0.15
    elif amt <= 100000:
        discount = 0.2
    else:
        discount = 0.3

amt_due = amt - (amt * discount)
print('---------------------------------------------------------')
print(f'Your total spending is ${amt}')
print(f'Based on your customer type, you are a {cust_type} customer')
print(f'Based on your selection, discount is {discount}')
print(f'Your final amount due is ${amt_due}')
            


What type of customer are you?: Corporate
What is the amount you spent?: 30000
---------------------------------------------------------
Your total spending is $30000.0
Based on your customer type, you are a Corporate customer
Based on your selection, discount is 0.25
Your final amount due is $22500.0


In [3]:
cust_type = input('What type of customer are you?: ')
amt = float(input('What is the amount you spent?: '))
            
if cust_type == 'Corporate':
    if amt <= 10000:
        discount = 0.2
    elif amt <= 40000:
        discount = 0.25
    elif amt <= 100000:
        discount = 0.3
    else:
        discount = 0.4
elif cust_type == 'Retail':
    if amt <= 10000:
        discount = 0.1
    elif amt <= 40000:
        discount = 0.15
    elif amt <= 100000:
        discount = 0.2
    else:
        discount = 0.3

amt_due = amt - (amt * discount)
print('---------------------------------------------------------')
print(f'Your total spending is ${amt}')
print(f'Based on your customer type, you are a {cust_type} customer')
print(f'Based on your selection, discount is {discount}')
print(f'Your final amount due is ${amt_due}')
            


What type of customer are you?: Retail
What is the amount you spent?: 30000
---------------------------------------------------------
Your total spending is $30000.0
Based on your customer type, you are a Retail customer
Based on your selection, discount is 0.15
Your final amount due is $25500.0


In [5]:
cust_type = input('What type of customer are you?: ')
amt = float(input('What is the amount you spent?: '))

if cust_type == 'Corporate' or cust_type == 'Retail':
    if cust_type == 'Corporate':
        if amt <= 10000:
            discount = 0.2
        elif amt <= 40000:
            discount = 0.25
        elif amt <= 100000:
            discount = 0.3
        else:
            discount = 0.4
    elif cust_type == 'Retail':
        if amt <= 10000:
            discount = 0.1
        elif amt <= 40000:
            discount = 0.15
        elif amt <= 100000:
            discount = 0.2
        else:
            discount = 0.3



    amt_due = amt - (amt * discount)
    print('---------------------------------------------------------')
    print(f'Your total spending is ${amt}')
    print(f'Based on your customer type, you are a {cust_type} customer')
    print(f'Based on your selection, discount is {discount}')
    print(f'Your final amount due is ${amt_due}')
            
else:
    print('Sorry, that customer type does not exist hence you are not eligible for discount')
    

What type of customer are you?: Yahoo
What is the amount you spent?: 30000
Sorry, that customer type does not exist hence you are not eligible for discount


In [14]:
cust_type = input('What type of customer are you?: ')
amt = float(input('What is the amount you spent?: '))
            
if cust_type == 'Corporate':
    if amt <= 10000:
        discount = 0.2
    elif amt <= 40000:
        discount = 0.25
    elif amt <= 100000:
        discount = 0.3
    else:
        discount = 0.4
        
    amt_due = amt - (amt * discount)
    print('---------------------------------------------------------')
    print(f'Your total spending is ${amt}')
    print(f'Based on your customer type, you are a {cust_type} customer')
    print(f'Based on your selection, discount is {discount}')
    print(f'Your final amount due is ${amt_due}')
    
elif cust_type == 'Retail':
    if amt <= 10000:
        discount = 0.1
    elif amt <= 40000:
        discount = 0.15
    elif amt <= 100000:
        discount = 0.2
    else:
        discount = 0.3
    amt_due = amt - (amt * discount)
    print('---------------------------------------------------------')
    print(f'Your total spending is ${amt}')
    print(f'Based on your customer type, you are a {cust_type} customer')
    print(f'Based on your selection, discount is {discount}')
    print(f'Your final amount due is ${amt_due}')
    
else: 
    print('You are not a valid customer')



            


What type of customer are you?: Corporate
What is the amount you spent?: 30000
---------------------------------------------------------
Your total spending is $30000.0
Based on your customer type, you are a Corporate customer
Based on your selection, discount is 0.25
Your final amount due is $22500.0


In [ ]:
if conditions:
    do something
elif conditions:
    do another thing
else:
    do something different

## For Loop
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

In [15]:
mylist = [1,2,3,4,5]
mylist

[1, 2, 3, 4, 5]

In [16]:
for i in mylist:
    print(i)

1
2
3
4
5


In [17]:
for element in mylist:
    print(element)

1
2
3
4
5


In [18]:
for j in range(3,17,2):
    print(j)

3
5
7
9
11
13
15


In [20]:
print(tuple(range(10)))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [22]:
for i in (1,2,3):
    print(i)

1
2
3


In [23]:
mylist2 = [1,2,3,4,5,6,7,8,9,10]
mylist2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
for k in mylist2:
    if k % 2 == 0:
        print(f'{k} is an even number')
        

2 is an even number
4 is an even number
6 is an even number
8 is an even number
10 is an even number


In [25]:
for k in mylist2:
    if k % 2 == 0:
        print(f'{k} is an even number')
    else:
        print(f'{k} is an odd number')

1 is an odd number
2 is an even number
3 is an odd number
4 is an even number
5 is an odd number
6 is an even number
7 is an odd number
8 is an even number
9 is an odd number
10 is an even number


In [26]:
mylist3 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
mylist3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [27]:
# add elements incrementally

sum_list = 0

for i in mylist3:
    sum_list = sum_list + i
    print(sum_list)

1
3
6
10
15
21
28
36
45
55
66
78
91
105
120


In [28]:
# compute the sum of all the elements

sum_list = 0

for i in mylist3:
    sum_list = sum_list + i

print(sum_list)

120


In [30]:
mylist4 = [11,16,17,19,25,27,30]

total_list = 0

for i in mylist4:
    total_list = total_list + i
    print(total_list)


11
27
44
63
88
115
145


In [31]:
mylist4 = [11,16,17,19,25,27,30]

totalList = 0

for i in mylist4:
    totalList = totalList + i
    print(totalList)
print(totalList)


11
27
44
63
88
115
145
145


In [32]:
# calculate total score from 5 tests scores

num_tests = [1,2,3,4,5]
total_score = 0


for num in num_tests:
    score = int(input('What is your score?  '))
    total_score += score
    print(total_score)
    
    


What is your score?  6
6
What is your score?  9
15
What is your score?  4
19
What is your score?  8
27
What is your score?  7
34


In [34]:
# calculate total score from 5 tests scores

num_tests = [1,2,3,4,5]
total_score = 0


for num in num_tests:
    score = int(input('What is your score?  '))
    total_score += score
print(total_score)
    
    


What is your score?  5
What is your score?  9
What is your score?  7
What is your score?  2
What is your score?  8
31


## While Loop

The while loop in Python is used to iterate over a block of code as long as the test expression (condition) is true.

We generally use this loop when we don't know the number of times to iterate beforehand.

In [35]:
name = input('What is your name?: ')

while name == 'Chinazam':
    print(f'Welcome to the class {name}!')
    name = input('What is your name?: ')

What is your name?: Chinazam
Welcome to the class Chinazam!
What is your name?: Chinazam
Welcome to the class Chinazam!
What is your name?: Fred


In [37]:
x = 0

while x < 10:
    print(f'{x} is currently less than 10')
    x += 1

0 is currently less than 10
1 is currently less than 10
2 is currently less than 10
3 is currently less than 10
4 is currently less than 10
5 is currently less than 10
6 is currently less than 10
7 is currently less than 10
8 is currently less than 10
9 is currently less than 10


In [38]:
answer = 'yes'

while answer == 'yes':
    name = input('What is your name?: ')
    question = input('What class did you enroll for?: ')
    print('------------------------------------------')
    print(f'Hello {name}')
    print(f'The class you enrolled for is {question} and will commence soon')
    answer = input('Do you want to continue: yes/no')

print('Goodbye')

What is your name?: Chinazam
What class did you enroll for?: Data Science
------------------------------------------
Hello Chinazam
The class you enrolled for is Data Science and will commence soon
Do you want to continue: yes/noyes
What is your name?: Abidemi
What class did you enroll for?: Financial Analysis
------------------------------------------
Hello Abidemi
The class you enrolled for is Financial Analysis and will commence soon
Do you want to continue: yes/noyes
What is your name?: Chuks
What class did you enroll for?: Data Analytics
------------------------------------------
Hello Chuks
The class you enrolled for is Data Analytics and will commence soon
Do you want to continue: yes/nocar
Goodbye


In [ ]:
# Flow Control

# pass - does nothing
# break - forces you out of the loop
# continue - lets you ignore a particular iteration result


In [39]:
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

for num in range(10):
    if num == 5:
        pass
    print(f'Number is {num}')

print('Out of loop')

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Number is 5
Number is 6
Number is 7
Number is 8
Number is 9
Out of loop


In [40]:
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

for num in range(10):
    if num == 5:
        break
    print(f'Number is {num}')

print('Out of loop')

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Out of loop


In [41]:
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

for num in range(10):
    if num == 5:
        continue
    print(f'Number is {num}')

print('Out of loop')

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Number is 6
Number is 7
Number is 8
Number is 9
Out of loop


## Function
In Python, a function is a group of related statements that performs a specific task.

Functions help break our program into smaller and modular chunks. As our program grows larger and larger, functions make it more organized and manageable.

Furthermore, it avoids repetition and makes the code reusable.

In [ ]:
# def name_of_function():
    '''This is where you enter a description of what your function does'''
    # do stuff here
    # return/print a result

In [42]:
def greeting():
    '''A function that returns Hello World'''
    print('Hello World!')
    

In [43]:
greeting()

Hello World!


In [44]:
def greet():
    '''A function that greets a person'''
    name = input('What is your name?: ')
    print(f'Hello, good day, how are you doing today, {name}? ')

In [45]:
greet()

What is your name?: Braimah
Hello, good day, how are you doing today, Braimah? 


In [46]:
def addnumbers(x,y):
    '''Add two numbers'''
    print(x+y)

In [48]:
addnumbers(5,6)

11


In [49]:
addnumbers(190,230)

420


In [50]:
addnumbers(50)

TypeError: addnumbers() missing 1 required positional argument: 'y'

In [51]:
def add(5,6):
    '''Add two numbers'''
    print(5+6)

SyntaxError: invalid syntax (<ipython-input-51-0cec606fdede>, line 1)

In [53]:
addnumbers(50)

TypeError: addnumbers() missing 1 required positional argument: 'y'

In [54]:
dir()

['In',
 'Out',
 '_',
 '_15',
 '_23',
 '_26',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'addnumbers',
 'amt',
 'amt_due',
 'answer',
 'cust_type',
 'discount',
 'element',
 'exit',
 'get_ipython',
 'greet',
 'greeting',
 'i',
 'j',
 'k',
 'mylist',
 'mylist2',
 'mylist3',
 'mylist4',
 'name',
 'num',
 'num_tests',
 'question',
 'quit',
 'score',
 'sum_list',
 'totalList',
 'total_list',
 'total_sc

In [61]:
def squarenum(x):
    '''Square a number'''
    return(x**2)

In [62]:
squarenum(100)

10000

In [64]:
z = squarenum(6) + 10
print(z)

46


In [59]:
a = z + 10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [65]:
z = squarenum(25)
a = z + 10
print(a)

635


In [66]:
squarenum

<function __main__.squarenum(x)>

In [67]:
def cubenum(x):
    '''Raise a number to power 3'''
    print(x**3)

In [68]:
m = cubenum(3)
n = m + 20
print(n)

27


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [71]:
def cubenums(x):
    '''Raise a number to power 3'''
    return(x**3)

In [73]:
m = cubenums(3)
n = m + 20
print(n)

47


In [83]:
def addition():
    '''Add numbers entered by a user'''
    total = 0
    for i in range(3):
        num = int(input('Enter a Number >>>>>>>  '))
        total += num
    return print(f'The sum of the numbers entered is {total}')
        
        
    

In [84]:
addition()

Enter a Number >>>>>>>  4
Enter a Number >>>>>>>  7
Enter a Number >>>>>>>  9
The sum of the numbers entered is 20


In [ ]:
print(mylist)

In [85]:
def addition():
    '''Add numbers entered by a user'''
    total = 0
    for i in range(5):
        num = int(input('Enter a Number >>>>>>>  '))
        total += num
    return print(f'The sum of the numbers entered is {total}')
        
        
    

In [86]:
addition()

Enter a Number >>>>>>>  4
Enter a Number >>>>>>>  7
Enter a Number >>>>>>>  9
Enter a Number >>>>>>>  3
Enter a Number >>>>>>>  2
The sum of the numbers entered is 25


In [87]:

def student_grade():
    ''' Return a letter grade based on a student's final score

     stud_name => student name
     first_test => score in first test
     second_test => score in second test
     attd => score in attendance
     exam => score in exam
     total_score => student's final score which is a summation of the above scores 
     assign a letter grade based on the student's final score

    '''

    stud_name = input('What is your name? >>>>> ')
    first_test = int(input('What is your score in first test? >>>>> '))
    second_test = int(input('What is your score in second test? >>>>> '))
    attd = int(input('What is your score in attendance? >>>>> '))
    exam = int(input('What is your score in the examination? >>>>> '))

    print('----------------------------------------------------------------')

    total_score = first_test + second_test + attd + exam

    if total_score >= 70:
        grade = 'A'
    elif total_score >= 60:
        grade = 'B'
    elif total_score >= 50:
        grade = 'C'
    elif total_score >= 40:
        grade = 'D'
    else:
        grade = 'F'

    print(f'Hello {stud_name}, your final score is {total_score} and your grade is {grade}')




In [88]:
student_grade()

What is your name? >>>>> Helen
What is your score in first test? >>>>> 25
What is your score in second test? >>>>> 19
What is your score in attendance? >>>>> 25
What is your score in the examination? >>>>> 22
----------------------------------------------------------------
Hello Helen, your final score is 91 and your grade is A


In [89]:
def return_grades(stud_name, f_test, s_test, attd, exam):
    ''' Return a letter grade based on a student's final score

     stud_name => student name
     first_test => score in first test
     second_test => score in second test
     attd => score in attendance
     exam => score in exam
     total_score => student's final score which is a summation of the above scores 
     assign a letter grade based on the student's final score

    '''
    total_score = f_test + s_test + attd + exam
    
    if total_score >= 70:
        grade = 'A'
    elif total_score >= 60:
        grade = 'B'
    elif total_score >= 50:
        grade = 'C'
    elif total_score >= 40:
        grade = 'D'
    else:
        grade = 'F'

    print(f'Hello {stud_name}, your final score is {total_score} and your grade is {grade}')



In [90]:
return_grades('Cynthia', 25, 23, 25, 20)

Hello Cynthia, your final score is 93 and your grade is A


## NUMPY - Numerical Python
- NumPy is the foundation of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors.

- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

In [2]:
mylist = list(range(1,11))
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(myarray)

numpy.ndarray

In [7]:
array1 = np.array([1,5,7])
array1

array([1, 5, 7])

In [8]:
# attribute - metadata about an object - no bracket ()
# method - a function associated with an object - methods have bracket()
# shape returns number of rows and columns (R X C)
myarray.shape

(10,)

In [9]:
# ndim returns number of dimensions

myarray.ndim

1

In [10]:
array2 = np.array([[1,5,7], [2,6,8]])
array2

array([[1, 5, 7],
       [2, 6, 8]])

In [11]:
# wrong 2d array creation

samplearray = np.array([1,5,7],[2,6,8])
samplearray

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [12]:
array2.shape

(2, 3)

In [13]:
array2.ndim


2

In [14]:
multiarray = np.array([[[1,3,5], [2,8,9], [5,3,7]]])
multiarray

array([[[1, 3, 5],
        [2, 8, 9],
        [5, 3, 7]]])

In [15]:
multiarray.shape

(1, 3, 3)

In [16]:
array3 = np.array([3])
array3

array([3])

In [17]:
array3.shape

(1,)

In [18]:
# size () number of items/elements in your array
array2.size

6

In [19]:
multiarray.size

9

In [20]:
x = list(range(1,5))
x

[1, 2, 3, 4]

In [21]:
# arange returns an array range

np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
# np.zeros()

np.zeros(5)


array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((5,5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.zeros((5,5), dtype=np.str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [30]:
np.zeros((5,5), dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [31]:
np.zeros((5,5), dtype=str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [32]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [33]:
np.array([1,2,3,4], dtype=np.str)

array(['1', '2', '3', '4'], dtype='<U1')

In [34]:
np.array([1,22,387,4], dtype=np.str)

array(['1', '22', '387', '4'], dtype='<U3')

In [35]:
# np.ones() returns all ones

np.ones(7)



array([1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
# np.eye() returns ones on the leading diagonal

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [39]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [40]:
# np.linspace() returns evenly-spaced numbers between a specified range

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [41]:
# when third argument is not included, it defaults to 50

np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [42]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [43]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [44]:
# np.full() returns a certain item throughout the array 

np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [45]:
np.full((3,4), 'garri')

array([['garri', 'garri', 'garri', 'garri'],
       ['garri', 'garri', 'garri', 'garri'],
       ['garri', 'garri', 'garri', 'garri']], dtype='<U5')

In [46]:
samplearray = np.array([[1,2,3],[4,np.nan,6],[np.nan,5,9]])
samplearray

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [nan,  5.,  9.]])

In [52]:
np.where(np.nan,samplearray,np.nanmean(samplearray))

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [nan,  5.,  9.]])

In [49]:
np.nanmean(samplearray)

4.285714285714286

In [50]:
np.mean(samplearray)

nan

In [53]:
array6 = np.array([1,2,3,4])
array6

array([1, 2, 3, 4])

In [54]:
array7 = np.array([4,5,6,7])
array7

array([4, 5, 6, 7])

In [55]:
# np.append() to merge two arrays

np.append(array6,array7)

array([1, 2, 3, 4, 4, 5, 6, 7])

In [ ]:
# Random 
# Rand
# Randn
# Randint

In [66]:
# rand return random numbers from a normal distribution

np.random.rand(10)

array([0.0365714 , 0.33398275, 0.28097267, 0.53835529, 0.38812432,
       0.92295906, 0.6284167 , 0.04141898, 0.53883335, 0.0467409 ])

In [67]:
np.random.rand(20)

array([0.24078012, 0.96772018, 0.0685751 , 0.3972247 , 0.54718485,
       0.89778076, 0.22691639, 0.45007333, 0.74731603, 0.26582731,
       0.17727984, 0.22448263, 0.38425065, 0.81117647, 0.12667139,
       0.51758247, 0.07801386, 0.48040014, 0.49774243, 0.29631165])

In [68]:
np.random.rand(2,4)

array([[0.97329927, 0.54719077, 0.63089319, 0.16826683],
       [0.69917961, 0.42754487, 0.86528782, 0.98722469]])

In [71]:
# randn returns random numbers from a standard normal distribution

np.random.randn(10)

array([ 0.25321593, -0.50921453,  0.38037876,  0.51240132,  0.58438026,
        0.64830494, -0.5562972 , -0.96832434,  0.86066835, -1.69578389])

In [88]:
# randint() returns a random number

np.random.randint(5)

2

In [109]:
np.random.randint(7,15)

12

In [124]:
np.random.randint(5,10,3)

array([7, 9, 7])

In [ ]:
# Indexing and Slicing

# array[R,C]

In [125]:
array2

array([[1, 5, 7],
       [2, 6, 8]])

In [126]:
array2[0]

array([1, 5, 7])

In [127]:
array2[1]

array([2, 6, 8])

In [128]:
array2[0][1]

5

In [129]:
array2[0,1]

5

In [ ]:
# [start:stop:step]

In [131]:
array2[:1]

array([[1, 5, 7]])

In [132]:
array2[:]

array([[1, 5, 7],
       [2, 6, 8]])

In [ ]:
# [R,C]
# [start:stop:step, start:stop:step]

In [133]:
array2[:,0]

array([1, 2])

In [134]:
array2[:,1]

array([5, 6])

In [135]:
array8 = np.array([[1,2,3],[4,5,6],[7,8,9],[5,3,8]])
array8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 3, 8]])

In [136]:
array8.shape

(4, 3)

In [137]:
array8[:,2]

array([3, 6, 9, 8])

In [138]:
array8[1:,]

array([[4, 5, 6],
       [7, 8, 9],
       [5, 3, 8]])

In [140]:
array8[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
# statistical functions

In [141]:
array8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 3, 8]])

In [142]:
np.mean(array8)

5.083333333333333

In [143]:
np.var(array8)

6.076388888888888

In [144]:
np.median(array8)

5.0

In [146]:
np.std(array8)

2.465033242958173

In [147]:
np.mean(array8, axis=0)

array([4.25, 4.5 , 6.5 ])

In [148]:
np.mean(array8, axis=1)

array([2.        , 5.        , 8.        , 5.33333333])